### ISSUE TITLE
A typo in wasm docs

### ISSUE THREAD

**Issue by steida** [cossacklabs/themis#894] opened 2022-01-02 14:33 UTC
Here https://docs.cossacklabs.com/themis/languages/wasm/installation/

```
node: {
    fs: 'empty'
}
```

Should be `ws`. Also, Webpack 5 has a different format:

```
config.resolve.fallback = {
      ...config.resolve.fallback,
      // Themis
      ws: false,
    };
```

**Comment by ilammy** [comment] 2022-01-05 10:14
@steida, I think `fs` is the correct one. There is [no Node.js module named `ws`](https://github.com/webpack/node-libs-browser#readme). This statement suppresses warnings from webpack caused by Node.js compatibility shims that Emscripten adds to generated code. They should never actually be used in Web environments, but exist in the code.

Do you experience issues with `fs` which get fixed by using `ws`? 🤔

**Comment by ilammy** [comment] 2022-01-05 10:15
Regarding webpack 5, you are absolutely right. I've filed a PR to provide an example for webpack 5 syntax. Thanks.

**Comment by steida** [comment] 2022-01-05 11:15
> @steida, I think `fs` is the correct one. There is [no Node.js module named `ws`](https://github.com/webpack/node-libs-browser#readme). This statement suppresses warnings from webpack caused by Node.js compatibility shims that Emscripten adds to generated code. They should never actually be used in Web environments, but exist in the code.
> 
> 
> 
> Do you experience issues with `fs` which get fixed by using `ws`? 🤔 

It fixed my code, that's why I made an issue. But I already deleted experimentach Themis branche, so I can not retest it. 1mb gzipped for web is no-go.

**Comment by vixentael** [comment] 2022-01-05 11:17
thank you guys! The docs are updated
https://docs.cossacklabs.com/themis/languages/wasm/installation/

**Closed** 2022-01-05 11:18 UTC
