### ISSUE TITLE
Can't decrypt messages between iOS and Android

### ISSUE THREAD

**Issue by iONsky** [cossacklabs/themis#220] opened 2017-08-29 18:37 UTC
Hello,

in my iOS app I'm using `themis 0.9.4` to encrypt and decrypt text messages and exchange them between two users. I do it by sharing the public key and use that to encrypt the message.  
Now I started developing an android client and included also `themis 0.9.4` by building it with `boringSSL`. I applied the same logic to encrypt and decrypt the messages but I can't decrypt them on iOS and the other way around.
I even tried to use the same private and public key on both platforms but that didn't work either.
Can someone please help me?

Thank you in advance

### iOS
Key generation:
`let keyGenerator = TSKeyGen(algorithm: .EC)`

Encryption:
`
let tsmessage = TSMessage(inEncryptModeWithPrivateKey: privateKey, peerPublicKey: peerKey)  
tsmessage.wrap(message.data(using: String.Encoding.utf8))
`

Decryption:
`tsmessage.unwrapData(data)`

### Android
Key generation
`Keypair pair = KeypairGenerator.generateKeypair(AsymmetricKey.KEYTYPE_EC);`

Encryption:
`
SecureMessage secureMessage = new SecureMessage(privateKey, peerKey);
secureMessage.wrap(message.getBytes("UTF-8")
`
Decryption:
`secureMessage.unwrap(Base64.decode(message.getBytes(), Base64.NO_WRAP));`

**Comment by vixentael** [comment] 2017-08-30 19:01
Hi @iONsky :)

Thank you for posting an issue instead of (╯°□°）╯︵ ┻━┻

I'm sure that the problem is super-simple. Let's try to check things one by one.

- [ ] iOS project itself. When you generate keypair, wrap and unwrap message, everything is okay? Just to make sure that you set up Themis on iOS correctly.
- [ ] Android project itself. When you generate keypair, wrap and unwrap message, everything is okay? Just to make sure that you set up Themis on Android correctly.

- [ ] Generate keys on iOS, encrypt the message and transfer them to the Android project. Make sure that you can decrypt the message using same keys on Android.

This is a tricky point. The problem might be in sending/receiving data (keys and payload) from one eco-system to another.

We build a [Themis server simulator](https://github.com/cossacklabs/themis/wiki/Using-Themis-Server) to make it easy to debug packing/unpacking issues. I would recommend you to connect both your projects to the Interactive server; it allows to check that Secure Message works for iOS and Android projects separately.

We have two examples that works with Themis server:

Swift example
https://github.com/cossacklabs/themis/tree/master/docs/examples/Themis-server/swift

Java example
https://github.com/cossacklabs/themis/tree/master/docs/examples/Themis-server/java

Please follow this README, it's really simple step by step guide that helps to understand how to send/receive data to/from server.
https://github.com/cossacklabs/themis/tree/master/docs/examples/Themis-server/swift#secure-message-mode

- [ ] Check that iOS and Android projects works correctly with Themis Server Simulator in Secure Message mode.

If nothing helps, please, attach your sample projects, so I can look more deep into them.

Thank you!

**Comment by vixentael** [comment] 2017-09-05 17:32
Hi

Any progress? Can I help you with anything?

Sooner or later we plan to create iOS-Android example project. It would help if you share your project.

**Comment by iONsky** [comment] 2017-09-05 19:22
Hey,
thanks for the quick and very detailed answer 👍 
I tried a couple of the things you suggested.
- [x] iOS project itself. When I generate keypair, wrap and unwrap message, everything is okay.
- [x] Android project itself. When I generate keypair, wrap and unwrap message, everything is okay.
- [x] Check that iOS project works correctly with Themis Server Simulator in Secure Message mode.
- [x] Generate keys on iOS and Android and transfer them to the other project. Encrypt and decrypt messages with those keys.
- [ ] **This fails!** Generate keys on iOS, **encrypt the message** and transfer them to the Android project. Make sure that you can decrypt the message using same keys on Android.
- [ ] **This fails!** Check that Android project works correctly with Themis Server Simulator in Secure Message mode.

I created an android test project and included only the themis lib. Same error. (I will attach it here soon)
I guess there is something wrong with the themis lib I build for Android.
Would it be possible for you to send me a already compiled themis lib for Android?

Thanks

**Comment by iONsky** [comment] 2017-09-05 20:34
I use the following script to build the lib. Maybe there is something wrong with that.

> #!/bin/bash
export ANDROID_HOME="/Library/Android/sdk"
export ANDROID_NDK="/Library/Android/sdk/ndk_bundle"
export ANDROID_NDK_ROOT="/Library/Android/sdk/ndk_bundle"
VERSION="0.9.4"
echo "Build boringSSL"
echo ""
mkdir themis
cd themis
git clone https://boringssl.googlesource.com/boringssl && cd boringssl && git checkout chromium-stable && mkdir build && cd build && cmake .. && make && cp decrepit/libdecrepit.a crypto/ && cd ../..
cd boringssl && mkdir build-armeabi-v7a && cd build-armeabi-v7a && cmake -DANDROID_ABI=armeabi-v7a -DCMAKE_TOOLCHAIN_FILE=../third_party/android-cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -GNinja .. && ninja && cd ../..
cd boringssl && mkdir build-arm64-v8a && cd build-arm64-v8a && cmake -DANDROID_ABI=arm64-v8a -DCMAKE_TOOLCHAIN_FILE=../third_party/android-cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -GNinja .. && ninja && cd ../..
cd boringssl && mkdir build-x86 && cd build-x86 && cmake -DANDROID_ABI=x86 -DCMAKE_TOOLCHAIN_FILE=../third_party/android-cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -GNinja .. && ninja && cd ../..

> echo "Build themis"
echo ""
curl https://codeload.github.com/cossacklabs/themis/zip/$VERSION --output themis.zip
unzip themis.zip
rm themis.zip
cd themis-$VERSION
./gradlew --info -Pboringssl_path=$(pwd)/../boringssl build
cp ./build/outputs/aar/themis-$VERSION-release.aar ../../app/libs/themis-$VERSION.aar

**Comment by vixentael** [comment] 2017-09-06 15:00
Awesome, so we narrowed the problem scope to the Android part of project!

Now our main goal is to make sure that your Android project with Themis lib works correctly with Themis Server simulator in Secure Message mode. This will indicate that everything is built and configured correctly.

Unfortunately we don't distribute Android wrapper as pre-compiled lib.

@secumod can you please take a look on the script that @iONsky is using.

Meanwhile, last time we got making issue it was solved by this comment 
https://github.com/cossacklabs/themis/issues/214#issuecomment-317377340


@iONsky 
By the way, Themis simulator has Android code as example, have you tried using it?
https://themis.cossacklabs.com/interactive-simulator/setup/

<img width="1160" alt="screen shot 2017-09-06 at 5 59 14 pm" src="https://user-images.githubusercontent.com/2877920/30119002-27cd63bc-932d-11e7-96da-b689dd949a5e.png">

**Comment by iONsky** [comment] 2017-09-18 19:22
So I finally got time to create a Android test project. I uploaded it to [Dropbox](https://www.dropbox.com/s/zlqjgmxpj2ph0yc/ThemisTestApp.zip?dl=0).  
But sadly it doesn't work with this either.  

I got it connected with the Themis Server simulator but it doesn't matter which keys or encoding methods I use it always fails with `Secure Message failed decrypting`

The code i used is mainly the example for Android (but I think the example is rather for plain Java) and modified a little bit to work for Android.

**Comment by vixentael** [comment] 2017-10-11 15:29
Thank you @iONsky :)

That was super-helpful. We are not ignoring you, we found some weird issues between Simulator and Android wrapper. We're debugging and testing it now.

Sorry for long silence, we hoped to fix it earlier, but :(

I'll let you know once it'll be fixed.

Thank you once again, based on your app, we'll update Android examples code.

**Comment by vixentael** [comment] 2017-12-04 16:11
Quick update :)

The problem with Android Secure Cell compatibility is confirmed, extracted and placed into different repository. Currently, data that was encrypted on Android using Secure Cell cannot be decrypted on any other platform. We can confirm that encryption itself is working (unit tests are passing, java tests are passing), however, there's smth in the whole Themis Android stack that makes it incompatible with any other platform (including Themis Secure Cell on pure Java).

Problem remains with Secure Message, but Secure Session is working fine.

Example project that illustrates issue between Android and pure Java is being provided below. It has long & careful description and current status.

https://github.com/vixentael/themis-android-compatibility-example

Current Themis Secure Cell compatibility matrix:

(was encrypted on .. / can be decrypted on ..)

| |	android	|	java	|	python	|	ruby	|	go	| ios	|
| --- |	---	|	---	|	---	|	---	|	---	|  --- 	|
| android	|	+		|   -		|	-		|	-		|	-	|	-	|
| java	|	-		|	+		|	+		|	+		|	+	|	+	|
| python	|	-		|	+		|	+		|	+		|	+	|	+	|
| ruby	|	-		|	+		|	+		|	+		|	+	|	+	|
| go 		|	-		|	+		|	+		|	+		|	+	|	+	|
| ios		|	-		|	+		|	+		|	+		|	+	|	+	|

We will work on this issue further (and add some integration tests to Themis as well).

**Comment by vixentael** [comment] 2017-12-23 14:23
Status update here.

I can confirm that Themis Secure Cell is **working properly between arm64 device and Java desktop app** (I was using real Android device, not emulator). I've tested on Android 7.1.2 (AOSP).

I can confirm that data encrypted on x86 Android emulator (tested on versions 7 and 8) can't be decrypted on real device, nor on Java desktop app. 

I'll update example repo's README accordingly.

Next steps of investigation: 
- test on arm64 emulator; 
- test on compiler optimizations (I'll try to build Themis with `-OS` flag).

**Comment by vixentael** [comment] 2018-01-07 15:51
Hi @iONsky!

First of all, thank you for your patience!

It looks like that the problem is not about Android-iOS, but between 32- and 64-bit architectures. If you are building your app for x64 infrastructure only, there should not be any compatibility issues. all modern iOS and Android devices are running on x64 chipsets. 

I'll close this issue, but provide all updates about 32/64 compatibility here as well.

**Closed by vixentael** 2018-01-07 15:51 UTC
Labels: android, bug, work in progress

**Comment by vixentael** [comment] 2018-01-18 11:54
Since #279 is merged, themis 0.9.7 will support encryption-decryption between x32-x64 systems :)

**Comment by vixentael** [comment] 2018-11-14 13:38
Hi again @iONsky :)

Sorry for disturbing, but I'm preparing a post on Cossack Labs web site to thank contributors and mention projects that use Themis. Don't you mind I ask you a for details of your project? 
Unfortunately I don't know you email, could you please ping me at vixentael@gmail.com?
